# Generated by Django 5.2.5 on 2025-09-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
