# Generated by Django 5.2.5 on 2025-09-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customerprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
    ]
