# Generated by Django 5.2.5 on 2025-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
